export enum LookupsRoutes {
 /* countries = 'countries',
  areas = 'areas',
  cities = 'cities',
  companyScale = 'company-scale',
  CompanyType = 'company-type',
  availableservices = 'available-services',
  shiftType = 'shift-type',
  timeType = 'time-type',
  BusinessType = 'business-type',
  BloodType = 'blood-type',
  FinanceYear = 'finance-year',
  Nationality = 'nationality',
  Gender = 'gender',
  timeZone = 'time-zone',
  jobtype = 'job-type',
  optionSet = 'option-set',
  optionSetItems = 'option-set-items',
  manageSetting = 'manage-setting',
  staticPages = 'static-pages',
  testNumber = 'test-number',*/
  customerManagement = 'customer management',
  MonitoringComplaints='monitoring complaints',
  infractionDetails='infraction Details'
}
