// Generated by https://quicktype.io

export interface OptionSetItems {
  id:        string;
  value:     number;
  nameAr:    string;
  nameEn:    string;
  optionSet: OptionSet;
  color:     string;
  isDefault: boolean;
  optionSetId:string
}
export interface OptionSet {
  id:             string;
  name:           string;
  displayNameAr:  string;
  displayNameEN:  string;
  optionSetItems: null[];
}
